version: "3.9"

services:
  node:
    build:
      context: .
    container_name: "dev"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - mongo
    networks:
      - mongo  
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo  
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: root
networks:
  mongo:
    driver: bridge