version: "3.9"

services:
  node:
    build:
      context: .
    container_name: "dev_api"
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/app  
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: root    